### ISSUE TITLE
On reproducing some fcn experiments

### ISSUE THREAD

**Issue by bobye** [shiba24/deep-learning-for-human-part-discovery-in-images#8]
I am now working to reproduce some experiments reported in the fcn paper. https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf

Compared to the layer-by-layer refinement training reported in the paper, the current model is trained end-to-end. It is interesting to see how much differences it make. One thing I observed is that the bilinear interpolation initialization for deconvolution layer is essential, otherwise the model can not be properly trained. 

I will also include some pretrained models if needed.

**Comment by shiba24** [comment]
Thank you for sharing your findings! OK, let's see the result. I agree with you that end-to-end experiment would be interesting and important, for reproducing both of the the fcn paper and Oliveira paper.
You are very welcomed to report the results and commit them to readme in this repo!

The original paper by Oliveira is also trained layer-by-layer. So it might be useful if we could add some options in the training and model functions so that we can easily change layer-by-layer/end-to-end.
